# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1319498710);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1319498226);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.18");
user_pref("extensions.enabledItems", "firebug@software.joehewitt.com:1.7.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.18");
user_pref("extensions.firebug.currentVersion", "1.7.3");
user_pref("extensions.firebug.previousPlacement", 3);
user_pref("extensions.lastAppVersion", "3.6.18");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1322090100);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
